### ISSUE TITLE
Egy sor nincs fordítva

### ISSUE THREAD

**Issue by orozso** [TryHardDood/AdvancedKitsReloaded#1]
**Helló Benjamin / @TryHardDood!**

Észre vettem, hogy a _src/main/resources/messages_hu.properties_ fájl 64. sora (_next_use_  kulcsú) nincs lefordítva, ahogy a többi nyelvi állományban sem. Nem tudom hogy ez véletlen vagy direkt van így. 

További sikeres kódolást / pluginolást kívánok!

**Comment by benjaminforras** [comment]
Valóban nincs lefordítva, de ezt hamarosan megteszem.
A többi nyelvi fájlban azért nincsen lefordítva, mivel azokat mások fordították le.

Köszönöm, hogy jelezted.

**Comment by orozso** [comment]
Szívesen, máskor is :-)
