### ISSUE TITLE
Error when i want to use the kit or view it

### ISSUE THREAD

**Issue by FunkyNico** [TryHardDood/AdvancedKitsReloaded#13]
So it's dat, when i want to use the command /kit use or /kit view, buy etc... appears this error on the console:

http://pastebin.com/89Ua2edS

And if i want to give the kit from a sign appears this error:

http://pastebin.com/DafBE3hD

Please help.

**Comment by benjaminforras** [comment]
Fixed in: https://github.com/TryHardDood/AdvancedKitsReloaded/commit/acabd25ce62bcdccb9e5c759665a14a243c0aeb2
