### ISSUE TITLE
Multiworld 

### ISSUE THREAD

**Issue by benjaminforras** [TryHardDood/AdvancedKitsReloaded#15]
https://www.spigotmc.org/threads/advancedkits-reloaded.86707/page-9#post-2198745

**Comment by SlimeDog** [comment]
Thanks. I was just catching up my to-do list, and was going to enter this feature request, but you already did. You're so on top of it. :)

**Comment by SlimeDog** [comment]
Any hope of this making it into the plugin?

**Comment by benjaminforras** [comment]
It's already in the rewritten plugin.
I just have to finish some parts of the plugin before releasing it. ( Such as localization, a gui for the flags)

**Comment by benjaminforras** [comment]
But if you want to know how it'll work:
You'll have one file named (ex.) myKit.yml -> This will be the global config file for that kit
If you want to specify other flags values in a world (ex. world_the_end) you'll have to create an empty yml file called: myKit_world_the_end.yml. 
After you restart or startup the server it'll generate a template in that file where you can adjust the flags to your likings.

**Comment by SlimeDog** [comment]
Thanks for the info. It is unclear (to me) how that will work to expose kits only in specific worlds (and not in others). Can you say more? Any estimate for release date?

**Comment by benjaminforras** [comment]
Can't say exact release date, I'll try my best. ( But I get tired of work and I don't have much free time )

So basically when you create a kit the plugin will create a config file for the kit.
If you want to set different values for different worlds you'll need to create a file next to the original one which's name contains the kit name and the world name. ( Ex: myKit_world_the_end.yml ):
Then reload the plugin and the plugin will update the created file with the values. ( Which you can set to you likings ).

**Comment by SlimeDog** [comment]
Did you see my config.yml suggestion? Config file per-world is not optimal -- I have 23 worlds. :(

**Comment by benjaminforras** [comment]
You want different config for each world?

**Comment by SlimeDog** [comment]
Sort of. In some cases, I would like to share kits across my Factions worlds, for example. But I would settle for different kits in each world. Including no kits in some worlds.

**Comment by SlimeDog** [comment]
Well, you got the "no kits in some worlds" in 1.0.x. Thanks.
