### ISSUE TITLE
[Feature] Log coloration

### ISSUE THREAD

**Issue by SlimeDog** [TryHardDood/AdvancedKitsReloaded#17]
Please introduce a configuration option to disable formatting codes in log entries. I prefer plain text, no colors or etc. Make the default whatever you feel is most requested, but please give me the option.

**Comment by benjaminforras** [comment]
I started rewriting the plugin and I won't include colorized log messages. Thanks for the idea.

**Comment by SlimeDog** [comment]
Thank you. Very much appreciated. Optional is fine; some people like them.

**Comment by SlimeDog** [comment]
Thanks.
