### ISSUE TITLE
Could you give me the changelog ?

### ISSUE THREAD

**Issue by TheIntelloBox** [TryHardDood/AdvancedKitsReloaded#18]
Hello !

All is in the title ! Could you give me the changelog ?

Thanks !

**Comment by benjaminforras** [comment]
Hello!

- Whole plugin have been rewritten.
- Added new flagsystem, new flags: spewitems, customdescription, potioneffects, particleeffects, soundeffects.
- Added perworldflags (You can find more info soon on the wiki)
- Added PlaceholderAPI support.
- More lightweight. (It runs faster)

Also you can check out this link: https://github.com/TryHardDood/AdvancedKitsReloaded/compare/3.0.29-36...master

**Comment by TheIntelloBox** [comment]
If I download the new update, the config will be automatically updated ?

**Comment by benjaminforras** [comment]
If you download the latest version of the plugin: https://github.com/TryHardDood/AdvancedKitsReloaded/releases/tag/v1.0.1

You won't have any problems with it.
