### ISSUE TITLE
JsonSyntaxException on start-up

### ISSUE THREAD

**Issue by SlimeDog** [TryHardDood/AdvancedKitsReloaded#20]
## What steps will reproduce the problem?  
Start server

## What were you expecting to happen? What happened instead?  
Expected: clean start-up
Experienced: Json syntax exception

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.0.1 (internally still 1.0.0)

## What Spigot version are you using? *Type /version*  
1.11.2 latest

## What plugins are you using? *Type /plugins*  
Many

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/gyHZyYG6

## Additional information?  *(Did it work in previous versions? etc.)*
Worked correctly with AKR 3.0.29-36.
Failed with NPE with AKR 1.0.0.

**Comment by SlimeDog** [comment]
Kit was altered by the plugin. 

Previous (3.0.29) content: https://pastebin.com/8FpWGZQi
New (1.0.1) content: https://pastebin.com/zQQvg7s3

**Comment by benjaminforras** [comment]
The plugin converted it to the right format but for some reason it did it by adding unneeded linebreaks

**Comment by benjaminforras** [comment]
Are you using linux?

**Comment by benjaminforras** [comment]
Could you try this version? It's working for me.
[AdvancedKitsReloaded.zip](https://github.com/TryHardDood/AdvancedKitsReloaded/files/959471/AdvancedKitsReloaded.zip)

**Comment by SlimeDog** [comment]
Yes. Linux. The plugin must support Linux file formats. I have to be able to edit the files. :(

**Comment by SlimeDog** [comment]
JsonSyntaxException with AKR 1.0.2-pre: https://pastebin.com/NKq2q8C6

**Comment by SlimeDog** [comment]
Converting kit files to DOS format (unix2dos utility) did not help. Similar error.

**Comment by benjaminforras** [comment]
When the plugin converts the files it puts whitespaces in the json string and I don't know why. On windows it's working fine.

**Comment by benjaminforras** [comment]
The file should look like this: https://pastebin.com/2J6a71Jz

**Comment by TryHardDood** [comment]
Please try this one. It should work.
[AdvancedKitsReloaded.zip](https://github.com/TryHardDood/AdvancedKitsReloaded/files/959504/AdvancedKitsReloaded.zip)

**Comment by benjaminforras** [comment]
Could you test it with this?
I can't reproduce the bug so I can't test it.

**Comment by SlimeDog** [comment]
I restored the original files from backup.

JsonSyntaxException on AKR 1.0.2-pre2 (the one immediately above): https://pastebin.com/DdY0gbQv

File content is significantly different from that pasted above, but there is no whitespace in the JSON strings.

**Comment by SlimeDog** [comment]
I'm on a test server, so I'm in no hurry. It would be painful to regenerate the kits from scratch, but not impossible. I cannot speak for others, of course. Production server remains on AKR 3.0.29-36.

**Comment by benjaminforras** [comment]
Thanks for helping!

**Comment by SlimeDog** [comment]
If you want to post a debug version, I would be happy to run it and post the results.

**Comment by benjaminforras** [comment]
Please try this version. I think I found the bug.
[AdvancedKitsReloaded.zip](https://github.com/TryHardDood/AdvancedKitsReloaded/files/959580/AdvancedKitsReloaded.zip)

**Comment by SlimeDog** [comment]
That seems to have fixed it. No start-up error, and I can view kits. Wasn't there a **/kit give** command?

**Comment by benjaminforras** [comment]
I think I left that one out

**Comment by SlimeDog** [comment]
Are you going to add it?

**Comment by benjaminforras** [comment]
Of course. I just forgot to add it :)

**Comment by SlimeDog** [comment]
When I view a kit, I don't see the "buy" option. (The kit is free.)

**/kit buy theSheriff** returns success, but I don't get the kit. Am I doing something wrong?

**Comment by benjaminforras** [comment]
I didn't add action buttons to the view gui but I'll thanks for the idea

**Comment by benjaminforras** [comment]
If you have more idea open an issue with [Feature] tag and I'll add those tomorrow
