### ISSUE TITLE
View kits shows incorrect icons

### ISSUE THREAD

**Issue by SlimeDog** [TryHardDood/AdvancedKitsReloaded#24]
## What steps will reproduce the problem?  
/kit view

## What were you expecting to happen? What happened instead?  
Expectation: View inventory of kits, with assigned icons.
Result: All kits are represented by gunpowder.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.0.2

## What Spigot version are you using? *Type /version*  
1.11.2 latest

## What plugins are you using? *Type /plugins*  
Many

## Additional information?  *(Did it work in previous versions? etc.)*
Worked correctly in AKR 3.0.29-36 and previous.
Failed in AKR 1.0.0 and following, including AKR 1.0.2.

Configuration example:
> Flags:
  visible: true
  permission: advancedkits.kit.use.theSheriff
  clearinv: false
  firstjoin: false
  replacearmor: false
  cost: 0
  uses: 0
  delay: 0.0
  icon: EMERALD_BLOCK
  global:
    delay: 0.0
    visible: true
    cost: 0
    firstjoin: false
Items:
...

**Comment by SlimeDog** [comment]
Isn't this a bug? The configured icon should be displayed.

**Comment by benjaminforras** [comment]
The icon flag was removed
