### ISSUE TITLE
Bug with the 1.0.4 (Pre-Release).

### ISSUE THREAD

**Issue by TheIntelloBox** [TryHardDood/AdvancedKitsReloaded#31]
Hi ! :D 

When we do /akit view, it works very fine, thanks my friend, thanks. :D 
But when we select a kit, and when we have got Essentials, it says : The player was not be found.

Sorry to say that, but the version 3 was better. x)

Thanks ! :D 
TheIntelloBox.

**Comment by benjaminforras** [comment]
Disable the kit command in the essentials' config.yml

**Comment by TheIntelloBox** [comment]
No, I use the /kit.

**Comment by benjaminforras** [comment]
You mean the Essentials' /kit command?

**Comment by TheIntelloBox** [comment]
Yes.

**Comment by benjaminforras** [comment]
Then just use /akit
