### ISSUE TITLE
Plugin does not start

### ISSUE THREAD

**Issue by TheUserDead** [TryHardDood/AdvancedKitsReloaded#34]
## What steps will reproduce the problem?  
1. 
Start the server
## What were you expecting to happen? What happened instead?  
Plugin does not load
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.1.2
## What Spigot version are you using? *Type /version*  
git-Spigot-3fb9445-fbb47e8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT) ----latest
and
git-Spigot-a3f6ea5-a2af8f0 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT) ----before
## What plugins are you using? *Type /plugins*  
I purge all plugins and use only AdvancedKitsReloaded and latest Vault (1.5.6-b49)
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/tbRTApH9
## Additional information?  *(Did it work in previous versions? etc.)*
I don't know works it in old versions or no (i lying, 1.1.1 not work too), cause i see essentials listening command /kit when i try disable essentials i see something does not work. I try to update all what i have and it's not help. (Sorry for my english)

**Comment by benjaminforras** [comment]
For some reason the plugin can't find Vault.

**Comment by TheUserDead** [comment]
I can fix this?
or 
I need to wait for your fix?
Cause i use latest version of vault :\

**Comment by benjaminforras** [comment]
First there's a important bug I need to fix. ( Without that you can't use the plugin at all ) then I'll try to fix this. But for some users it works perfect.

**Comment by benjaminforras** [comment]
Install Essentials or some kind of economy plugin which supports Vault

**Comment by TheUserDead** [comment]
I try load the plugin and i have no errors, but plugin does not react on /kit /akit /advancedkit and have nothing on console

**Comment by benjaminforras** [comment]
Do you have an economy plugin on the server? Did the plugin started up? Without log I can't do much.

**Comment by TheUserDead** [comment]
i mean only commands, no errors.
Using Vault (i say about version before)
Essentials-2.x-SNAPSHOT (spigot) (build 21)

**Comment by TheUserDead** [comment]
okay, i understand, here's pastebin log https://pastebin.com/eFfgUbEu

**Comment by benjaminforras** [comment]
**Edit:** 
Your problem is you didn't type a valid command. Check out the commands wiki: [4. Commands](https://github.com/TryHardDood/AdvancedKitsReloaded/wiki/4.-Commands)

**Comment by TheUserDead** [comment]
Of couse, i'm Admin Setting up the Server have Op and *.* permission

**Comment by benjaminforras** [comment]
> Edit:
> Your problem is you didn't type a valid command. Check out the commands wiki: [4. Commands](https://github.com/TryHardDood/AdvancedKitsReloaded/wiki/4.-Commands)

**Comment by TheUserDead** [comment]
Oh, really, thank you very much!
