### ISSUE TITLE
Kits Command and help not showing

### ISSUE THREAD

**Issue by Hellcode48** [TryHardDood/AdvancedKitsReloaded#43]
## What steps will reproduce the problem?  
1. type /kit or /kits
2. type /kit help

## What were you expecting to happen? What happened instead?  
I expect /kit and /kits to open GUI to show kits, but nothing happens with no errors

I expect /kit help to show me the AdvancedKits Help Page, but nothing shows with no errors

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
Version 1.1.5

## What Spigot version are you using? *Type /version*  
git-Spigot-3fb9445-2b6c9f4 (MC: 1.11.2) {Implementing API version 1.11.2-R0.1-SNAPSHOT)

## What plugins are you using? *Type /plugins*  
Plugins (146): EasyElevators, LampControl, FurnaceNotify, PlugMan, AdvancedShulkerboxes, PowerNBT, BanManager, Arconix, PathWays, DamageIndicator, UltimateTroll, ThisLogMustDie, FalcaoCore, BuildingTools, MinecraftMarket, AsyncWorldEditInjector, AnimationLib, Skript, AntiChorusFruit, NBTEditor, FlagsCopy, Multiverse-Core, ProtocolLib, VoidSpawn, AdvancedPortals, PermissionsEx, Zenchantments, mcMMO, RPGHealthIndicator, Questioner, JoeIPTracker, PlaceholderAPI, BetterCrops, DeluxeCommands, BetterChairs, MyItems, AdvancedLogger, NoElytra, VoxelSniper, EpicWorldGenerator, ParticleLIB, ShutdownNotice, TreeFeller, CoreProtect, ChatAPI, EnderWays, Graveyards, AnimatedNames, WorldBorder, Votifier, BannerBoard, RandomStuff, LibsDisguises, SafariNet, AsyncWorldEdit, WorkbenchKeeper, Emotes, PastebinLog, EffectLib, CS-CoreLib, Vault, ColoredAnvils, LlamaBorn, BloodInMinecraft, Clickssentials, WitcherPotions, LWC, HolographicDisplays, ZHorse, VoteParty, ChatItem, AdvancedKitsReloaded, Multiverse-NetherPortals, RepairPlus, EpicNetherGenerator, RunesEnchant, MagicCrafting, FoodMC, mcMMOAction, MessageAnnouncer, Citizens, TradeMe, Shopkeepers, OnTime, CrazyAuctions, NPC_Destinations, GAListener, DabCore, Pl3xRTP, WorldEdit, CrazyEnchantments, Denizen, Essentials, RichMobs, Towny, HeadDatabase, McMMOExtras, BannerMaker, ZQuest, AnimatedMenuPlus, JLib, CitizensText, CMI, ZQEx-MCMMO, TownyNameUpdater, Shop, ServerSigns, CommandNPC, QuickSell, PremiumVanish, NPCDestinations_Animator, Sentinel, TownyChat, WorldGuard, ItemLoreStats, ItemCommand, Slimefun, PvPManager, EssentialsSpawn, WorldGuardExtraFlags, AreaShop, ExoticGarden, CraftBook, NoFlyZone, TinkerTools, TitleManager, SlimeXpansion, HyperDrive, DeluxeChat, EmeraldEnchants, SlimefunLuckyBlocks, ArtMap, ChestShop, ArmorStandTools, ElectricSpawners, MagicLoot, ExtraHeads, Dolly, ProtectionLib, MysqlPlayerDataBridge, SoulJars, MentionMe, FurnitureLib, DiceFurniture, SelectionVisualizer, React

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
There are no errors, I triple checked

**Comment by TheIntelloBox** [comment]
Me too...
