### ISSUE TITLE
2 Big Bugs in 1.11.2 !

### ISSUE THREAD

**Issue by TheIntelloBox** [TryHardDood/AdvancedKitsReloaded#49]
Hello ! :D 

I have 2 big bugs with the latest release of the plugin on GitHub.
Minecraft version : 1.11.2 !
The first : In the /akit view, all the kits have the same name.
Screen : http://zupimages.net/up/17/20/jrsm.jpg

The second : When we do /akit use : we have a GUI where there isn't the kits, where there is nothing.
Screen : http://zupimages.net/up/17/20/b32f.jpg

Thanks !

**Comment by benjaminforras** [comment]
For me it's working.
You don't see kits in the /akit use gui because you haven't unlocked​ any kit. (Or there's no free kits)

**Comment by TryHardDood** [comment]
For me it's working.
You don't see kits in the /akit use gui because you haven't unlocked​ any kit. (Or there's no free kits)

**Comment by TheIntelloBox** [comment]
I'm op so I have all the permissions so why aren't the kits unlocked for me ?
And for my first bug, it's a bug because all the kits are named "Vipere".

**Comment by benjaminforras** [comment]
You haven't unlocked the kits this is why it's not showing up.
Could you send me your kits folder?

**Comment by TheIntelloBox** [comment]
How do I give you it please ? :D

**Comment by benjaminforras** [comment]
Upload it here in a zip file

**Comment by TheIntelloBox** [comment]
Edit: Removed to avoid copying
