### ISSUE TITLE
Permission.

### ISSUE THREAD

**Issue by TheIntelloBox** [TryHardDood/AdvancedKitsReloaded#52]
Hi ! :D 

My suggestion is easy : 
For example, if you have the permission : advancedkits.use.Test, when you do /akit use, I want that the players doesn't have to buy the kit. 
So I want that if you have a permission, when you do /akit use the kit is in the GUI, without buying it, if it's free.

Thanks !

**Comment by benjaminforras** [comment]
Hi. Just set the FREE flag to true
