### ISSUE TITLE
Bug in the /akit buy

### ISSUE THREAD

**Issue by TheIntelloBox** [TryHardDood/AdvancedKitsReloaded#53]
Hi !

When I do /akit buy, and when I click on the sign at the bottom, it shows me the second page but it says in the tchat : "Kit not found". I have the same thing when I want to go from the second page to the first.

Thanks ! :D

**Comment by benjaminforras** [comment]
Hi!
Thanks for reporting it.
Does it turns the page after you clicked?

**Comment by TheIntelloBox** [comment]
Yes. :)

**Comment by benjaminforras** [comment]
Please redownload the plugin from here: (This contains the fix)
Thanks for reporting.
[v1.1.13](https://github.com/TryHardDood/AdvancedKitsReloaded/releases/tag/v1.1.13)
