### ISSUE TITLE
My Players can do /akit use many times.

### ISSUE THREAD

**Issue by TheIntelloBox** [TryHardDood/AdvancedKitsReloaded#54]
Hi again,

My players can, for example, do /akit use Test and /akit use Test2 so they can improve and merge their kits.
How can I solve it ?

Thanks ! :D

**Comment by benjaminforras** [comment]
I don't understand your problem. Could you explain it more?

**Comment by TheIntelloBox** [comment]
They can merge kits but I don't want that.

**Comment by TheIntelloBox** [comment]
Could you add a way that if we do /akit use, our inventory is clear ?

**Comment by benjaminforras** [comment]
Set the clearinventory flag to true
Read the wiki please
https://github.com/TryHardDood/AdvancedKitsReloaded/wiki/Flags
