### ISSUE TITLE
Lang.yml file. ^^

### ISSUE THREAD

**Issue by TheIntelloBox** [TryHardDood/AdvancedKitsReloaded#55]
Hi ! :D 

Could you do a lang.yml file ? It's better than the current file, I think. :)

Thanks ! :D

**Comment by benjaminforras** [comment]
What difference would it make?

**Comment by TheIntelloBox** [comment]
It's better. :)

**Comment by benjaminforras** [comment]
I don't know what you want. There's a language file.
