### ISSUE TITLE
Flags does not work or i forgot something?!

### ISSUE THREAD

**Issue by TheUserDead** [TryHardDood/AdvancedKitsReloaded#56]
## What steps will reproduce the problem?  
1. 
I try ti setting up kit flags for limiting use kits by time (like one per day and 10 call limit)
## What were you expecting to happen? What happened instead?  
I can call kit unlimited times
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.1.13
## What Spigot version are you using? *Type /version*  
git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2)
## What plugins are you using? *Type /plugins*  
Vault  v1.5.6-b49
Essentials-Spigot 2.x-SNAPSHOT
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
Nothing special for display in log, have no errors
## Additional information?  *(Did it work in previous versions? etc.)*
My config for example here https://pastebin.com/US4dEmqS

**Comment by benjaminforras** [comment]
What does the plugin say in the chat?

**Comment by TheUserDead** [comment]
Nothing special. In console only "User issued server command: /kit"
And nothing later
In game i type /kit
And see GUI
I mouse over on kit like start or food ind i see desc and info about using
They have limits for call (1 call per day) food (30min per call and limit for 1 call)
i setting up all flags from game in OP account (User have basics permissions advancedkits.player and advancedkits.use.start)
when i click green button i give kit but, i can click again and give items before cooldown!
Here screen about problem (you can see desc and my invertory) https://www.dropbox.com/s/wdy40qe6hsroci3/2017-05-28_22.14.27.png?dl=0
and if i click later i can give message about overload invertory

**Comment by benjaminforras** [comment]
I see. I'll look into it
