### ISSUE TITLE
The flag "delay" doesn't work

### ISSUE THREAD

**Issue by AndyYu168** [TryHardDood/AdvancedKitsReloaded#57]
## What steps will reproduce the problem?  
1. I want to set the flag "delay" for my kit, but it doesn't work at all, my players can use the kit at any time without any limit
2. I gave these permissions to my players: advancedkits.player advancedkits.use.kitname  
## What were you expecting to happen? What happened instead?  
I want delay between uses, but it doesn't work.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.1.13 (the latest)
## What Spigot version are you using? *Type /version*  
git-Spigot-7d78b81-746cf0f (MC 1.11.2)
## What plugins are you using? *Type /plugins*  
Just some common plugins, like Vault, Essentials, all my plugins are the latest.
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No, nothing special in my log, and I can't see any error message in game.
## Additional information?  *(Did it work in previous versions? etc.)*
None

**Comment by benjaminforras** [comment]
Thanks for reporting. I'll look into it as soon as I can.
