### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by gxnni** [TryHardDood/AdvancedKitsReloaded#58]
Could there be another plugin interfering?  

![screen shot 2017-06-03 at 1 43 36 am](https://cloud.githubusercontent.com/assets/29157581/26751058/c8126bda-47fe-11e7-92f2-feb9f5535c0f.jpg)

**Comment by TryHardDood** [comment]
Please send more details. Ex. Console log, server version, plugin version

_Sent from my Xiaomi Redmi Note 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by benjaminforras** [comment]
Please send more details. Ex. Console log, server version, plugin version

**Comment by gxnni** [comment]
The server is running Bukkit version 1.12, and here is the output when starting the server:

[Terminal Output Porblem With AdvancedKitsReloaded.zip](https://github.com/TryHardDood/AdvancedKitsReloaded/files/1049673/Terminal.Output.Porblem.With.AdvancedKitsReloaded.zip)

**Comment by benjaminforras** [comment]
[11:20:57 INFO]: [AdvancedKits] - Disabled due to no Economy plugin found!

**Comment by gxnni** [comment]
Oh LMAO can you send me the link to the best plugin to use

**Comment by benjaminforras** [comment]
Essentials :)

**Comment by gxnni** [comment]
I have essentials! Its just not working still

**Comment by benjaminforras** [comment]
It should. Console log?

**Comment by gxnni** [comment]
[Terminal Output.zip](https://github.com/TryHardDood/AdvancedKitsReloaded/files/1049890/Terminal.Output.zip)

**Comment by benjaminforras** [comment]
```
[16:16:40 ERROR]: java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.maximumSize(I)Lcom/google/common/cache/CacheBuilder;
[16:16:40 ERROR]: Error occurred while enabling Essentials v2.13.1 (Is it up to date?)
```
Use this version of Essentials (this supports Minecraft 1.8 and up.): https://www.spigotmc.org/resources/essentialsx.9089/

**Comment by gxnni** [comment]
It works now, thank you!

**Comment by benjaminforras** [comment]
No problem.
