### ISSUE TITLE
It's not working in my server 

### ISSUE THREAD

**Issue by TommyVic** [TryHardDood/AdvancedKitsReloaded#59]
When i add this plugin to my server it's not working It's still create a file but it's not working ingame 
all the command not show up, i can't even /help 
I'm using 1.11.2-R0.1 SNAPSHOT version for my server
The plugin i'm using is AdvancedKits Reloaded and i'm using the lastest version
It's doesn't have any error log
I haven't use it in the last version so idk

**Comment by benjaminforras** [comment]
Can you give me the followings?
- Server type
- Console log
- Generated file and it's content

**Comment by TommyVic** [comment]
Never mind it's work i have to restart my server again thank you <3

**Comment by benjaminforras** [comment]
No problem, have fun.
