### ISSUE TITLE
A question about flag "firstjoin"

### ISSUE THREAD

**Issue by AndyYu168** [TryHardDood/AdvancedKitsReloaded#63]
Hello bro, could you tell me what does the flag "firstjoin" mean?
I regard it as "players can get the kit when they join the server FOR THE FIRST TIME, but they can't if joining for the 2nd, 3rd time."
but actually I'm wrong, everytime I restart my server, my players can still get the kit with the flag "firstjoin" true (Test version:1.1.14  spigot 1.11.2)
Is this a bug or……there is something wrong with my understanding? it's just a normal feature? 
If it's just a feature, I think this flag is meaningless, I want my players get the kit only for the first join, not after my server restarted.

**Comment by LilWoofy** [comment]
Having this same issue.
