### ISSUE TITLE
Free Kits Bug  (renaming chests)

### ISSUE THREAD

**Issue by SoyDary** [TryHardDood/AdvancedKitsReloaded#64]
Any user can rename a chest in an anvil by putting "kit"
And when you put the chest you can get the kit items completely free

I would appreciate if you touched that topic a bit since it is a very serious bug

![screenshot_52](https://user-images.githubusercontent.com/30793634/29017757-daf6bd4e-7b1d-11e7-87c9-0289ba00c664.png)

**Comment by benjaminforras** [comment]
Hello
Thanks for reporting this bug.

Currently, I don't have much time for developing plugins but here's a workaround:
- Add colors to the display name so the players can't rename it in the anvil.
