### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Infiell** [TryHardDood/AdvancedKitsReloaded#66]
## What steps will reproduce the problem?  
1. When I write the commands of this plugin
## What were you expecting to happen? What happened instead?  
I expected something. In the end, nothing, even no mistakes
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
v1.1.14
## What Spigot version are you using? *Type /version*  
![ss 2017-08-09 at 05 56 59](https://user-images.githubusercontent.com/30868449/29125216-34f24da8-7d2c-11e7-8e11-be0c7a52459b.jpg)
## What plugins are you using? *Type /plugins*  
![ss 2017-08-09 at 05 58 04](https://user-images.githubusercontent.com/30868449/29125262-5e99bf42-7d2c-11e7-9ca2-eef2ca3645bc.png)
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
No mistakes

**Comment by benjaminforras** [comment]
Sadly, I don't know what causes the problem, I don't see anything bad.
