### ISSUE TITLE
Kits marked as `firstjoin: true` are given at each join

### ISSUE THREAD

**Issue by fax1ty** [TryHardDood/AdvancedKitsReloaded#73]
Kits marked as `firstjoin: true` are given at each join, not just the first one.

And if `maxuses: 1` on each join is written: "You can't use this kit more"

![image](https://user-images.githubusercontent.com/26363214/30521629-82a4756a-9bd3-11e7-8906-b40dd802b3b0.png)

**Comment by benjaminforras** [comment]
Which version are you using?
Try it with this one: https://github.com/TryHardDood/AdvancedKitsReloaded/releases/tag/v1.1.15-snapshot

**Comment by fax1ty** [comment]
1.1.14

**Comment by fax1ty** [comment]
https://github.com/TryHardDood/AdvancedKitsReloaded/issues/63
Oh, OK

**Comment by fax1ty** [comment]
https://github.com/TryHardDood/AdvancedKitsReloaded/issues/63
Oh, OK
