### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by benjaminforras** [TryHardDood/AdvancedKitsReloaded#9]
@renzotom

- Effects to kit (ex. gravity, luck...)
- Firework when use it, preview it....
- Particle when use it, preview it...
- Sound, when use it, preview it...
- Titles, subtitles, action bars, json messages....
- Way to broadcast some kits....

**Comment by renzotom** [comment]
When you think, new version will be?

**Comment by benjaminforras** [comment]
I have a lot of things to do now. But I'll try to release it as soon as I can.
